// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0giDefr_EMA5ce3mXJofzP6cTmQfcBvA',
    appId: '1:142726409576:android:ab3fedd3e9769098defadd',
    messagingSenderId: '142726409576',
    projectId: 'festival-post-58dc1',
    databaseURL: 'https://festival-post-58dc1-default-rtdb.firebaseio.com',
    storageBucket: 'festival-post-58dc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NTE_MyAI4bd6_fM3pVrPSDOd92Gtysw',
    appId: '1:142726409576:ios:3c61dd45d9573b26defadd',
    messagingSenderId: '142726409576',
    projectId: 'festival-post-58dc1',
    databaseURL: 'https://festival-post-58dc1-default-rtdb.firebaseio.com',
    storageBucket: 'festival-post-58dc1.firebasestorage.app',
    iosBundleId: 'com.example.festivalPost',
  );
}
